"""Change receipt_data to LONGBLOB

Revision ID: 512b1d553a4d
Revises: 
Create Date: 2025-02-27 10:27:14.481830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '512b1d553a4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_data',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('receipt_data',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('report_data',
               existing_type=sa.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('report_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.alter_column('receipt_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
